name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    steps:
    - name: Set Git's core.autocrlf to false for Windows before checkout
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "gradle"
    - name: Check
      run: ./gradlew --stacktrace check
